---
title: 'Project 1: Wrangling, Exploration, Visualization'
author: "SDS322E"
date: ''
output:
  html_document:
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
  pdf_document:
    toc: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, fig.align = "center", warning = F, message = F,
tidy=TRUE, tidy.opts=list(width.cutoff=60), R.options=list(max.print=100))
```

## Data Wrangling, Exploration, Visualization

### Sarah Isaack sji259

#### Introduction 

Paragraph or two introducing your datasets and variables, why they are interesting to you, etc.

```{R}
# read your datasets in here, e.g., with read_csv()
library(readr)
state_candy <- read_csv("/stor/home/sji259/project1/state_candy.csv")
state_candy
library(fivethirtyeight)
candy_rankings <- candy_rankings
```

#### Tidying: Reshaping

If your datasets are tidy already, demonstrate that you can reshape data with pivot wider/longer here (e.g., untidy and then retidy). Alternatively, it may be easier to wait until the wrangling section so you can reshape your summary statistics. Note here if you are going to do this.

```{R}
library(dplyr)
library(tidyr)
#My data was already tidy, so I will be untidying and retidying it#
state_candy_wide <- state_candy %>% pivot_wider(names_from="Top Candy", values_from="Pounds")
state_candy_wide %>% pivot_longer(2:20, names_to="Top Candy", values_to="Pounds") %>% na.omit

candy_rank_wide <- candy_rankings %>% pivot_wider(names_from="competitorname", values_from="winpercent")
candy_rank_wide %>% pivot_longer("100 Grand":"Whoppers", names_to="competitorname", values_to="winpercent") %>% na.omit
```
I did consider making the table longer so that all of the different flavor columns would just be in one column, however since one candy can have many different flavors, this made the resulting dataset incredibly long and cumbersome to work with. It also made it harder to see the relationships between the states and candies, which is what I am most interested in.
    
#### Joining/Merging

```{R}
joined_candy <- right_join(candy_rankings, state_candy, by=c("competitorname"="Top Candy"))
glimpse(joined_candy)
glimpse(candy_rankings)
glimpse(state_candy)
```

I decided to complete a right join with my two datasets so that I could more easily focus on the Halloween candy statistics specifically for all 50 states, and Washington D.C without seeing all of the NA values for the Halloween candies that were not a top choice of any state. In the two separate datasets, the candy_rankings dataset had 85 observations and 14 distinct variables while the state_candy dataset had 51 observations and 3 distinct variables. However, in this right join, there were 51 observations and they were joined using 1 distinct ID variable. However, this ID variable had different names in each dataset, which had to be accounted for. Because of this, all of the original variables from the two separate datasets were present in the joined dataset, however the "Top Candy" ID variable from the state_candy dataset combined with the "competitiorname" ID variable from the candy_rankings dataset. This resulted in 16 distinct variables in the joined dataset.The state_candy dataset kept all of its observations in the joined dataset, however the candy_rankings lost 34 observations which were of candies that were no state's favorite. 

ALSO THERE WERE -------- CANDIES THAT WERE IN THE STATE_CANDY BUT NOT IN THE CANDY_RANKINGS RESULTING IN ----- NAs.

####  Wrangling

```{R}
joined_candy %>% mutate(Kilograms=(Pounds*0.453592))
```

When using mutate, I created a variable called Kilograms which converts the pounds variable to show the amount of the specific Halloween candy bought in kilograms for the year of the study. 

```{R}
joined_candy %>% group_by(competitorname) %>% summarize(count=n_distinct(State)) %>% arrange(desc(count))

```
In order to visualize which Halloween candies were popular in the most states, I first used group_by to group all of the candies together, then I used summarize to count up the distinct states that each candy was the favorite of. Lastly, I arranged this count in descending order so that the most popular candies could be viewed. From this I gathered that Reese's cups, Sour Patch Kids, and Starburst are tied for most popular as they all are the favorite in 6 different states. Meanwhile, 3 Musketeers, Almond Joy, Blow Pops, Dubble Bubble Gum, Lemonheads, Milky Way, Swedish Fish, and Twix are all tied for least popular as they each only are the favorite of one state. 

```{R}
joined_candy %>% filter(Pounds == max(Pounds)) %>% select("competitorname","winpercent","State","Pounds")
joined_candy %>% arrange(desc(winpercent))
```

I was curious to know which candy had been purchased the most by weight. To figure this out, I filtered the joined_candy data so that the row with the highest Pound variable was chosen, then I selected the columns that I was interested in seeing, in this case, the columns for the candy name, the win percentage that the candy has when it went up against other candies, the state that bought the pounds of candy, and the number of pounds that were bought. I learned that California bought the most candy, which happened to be Reese's Peanut Butter Cups. It also worked out that this candy had the highest win percentage, which I found by arranging the data in a descending order according to win percentage. 

```{R}
library(knitr)
library(stringr)
joined_candy %>% summarize(mean_sugar=mean(sugarpercent, na.rm=T), sugar_sd=sd(sugarpercent, na.rm=T), sugar_var=var(sugarpercent, na.rm=T), n()) ->table1
table1 %>% kable(digits = 3, align = 'c', col.names=str_to_title(names(.)))
```
The numeric variable sugarpercent shows the percentile of sugar that a certain candy falls under within the data set. After using this variable to calculate some summary statistics, it is shown that the average of all the candies sugar content falls around the 47th percentile when rounded. The standard deviation in all the candies is 0.3207757 percentiles, and the variance between the candies is pretty low at 0.102897. Lastly, there are 51 different rows of candies for this variable. 

```{R}
library(knitr)
library(stringr)
joined_candy %>% summarize(mean_price=mean(pricepercent, na.rm=T), price_sd=sd(pricepercent, na.rm=T), price_var=var(pricepercent, na.rm=T), n()) -> table2
table2 %>% kable(digits = 3, align = 'c', col.names=str_to_title(names(.)))

```
The numeric variable price percent is a record of the price percentile per unit that the candy falls into in comparison with the other candies in the dataset. In order to compare this percentile calculation to the other percentile variable sugarpercent, I calculated the same summary statistics for both variables. For the average price percentile of these candies, it was found to be in about the 39th percentile. The standard deviation in price percentile was found to be 0.2537781 with a variance of 0.06440331. This shows that when compared to sugarpercent, pricepercent has on average a lower percentile, a lower standard deviation, and a lower variance. Likewise with sugarpercent, there are still 51 observations. 

```{R}
library(knitr)
library(stringr)
joined_candy %>% summarize(win_mean=mean(winpercent, na.rm=T)) -> table3
table3 %>% kable(digits = 3, align = 'c', col.names=str_to_title(names(.)))
joined_candy %>% group_by(chocolate) %>% summarize(winmean=mean(winpercent, na.rm=T), win_min=min(winpercent, na.rm=T), win_max=(max(winpercent, na.rm=T))) -> table4
table4 %>% kable(digits = 3, align = 'c', col.names=str_to_title(names(.)))
```
The next numeric variable I had was winpercent, which is the percentage that the candy in question won against 269,000 matchups with other candies. First, I wanted to see just the overall average of wins throughout all the candy in the data set. This came to be 64.548%, which means the candies in this dataset won 64.548% of the time,on average. Next, I wanted to see how just the chocolate group performed, and if they won more or less often than the entire group. After grouping by chocolate, the winning average fo candies that contained chocolate was 66.94112% while candies without chocolate won an average of 61.45102% of the time. I also found the minimum and maximum of the candies that had chocolate and those that don't. Candies that do have chocolate have a much higher maximum and minimum winning percent than candies without chocolate, which shows that chocolate-containing candies might be more popular. 

```{R}
library(knitr)
library(stringr)
joined_candy %>% summarize(avg_pound=mean(Pounds, na.rm=T), n_distinct(Pounds), max_pound=max(Pounds, na.rm=T), min_pound=min(Pounds, na.rm=T)) -> table5
table5 %>% kable(digits = 3, align = 'c', col.names=str_to_title(names(.)))
joined_candy %>% group_by(fruity, chocolate) %>% summarize(mean_weight=mean(Pounds, na.rm=T)) -> table6
table6 %>% kable(digits = 3, align = 'c', col.names=str_to_title(names(.)))
```
The last numeric variable is Pounds, which is the weight in pounds that each state bought of their favorite candy. First, I wanted to just see some characteristics about this variable. I found that the mean pounds of candy bought overall was 159,803.5 lbs with a max of 1,209,299 lbs and a min of 2873 lbs. 
Next, I wanted to see if the type of candy had any effect on the number of pounds bought, so I grouped by fruity type and chocolate type to see any differences. I found that candies that were only chocolate flavored had been bought for 175,840.3 lbs on average, candies that were only fruity had been bought for 128,243.8 lbs on average, and candies that were both fruity and chocolate type had been bought for 207,222.0 lbs on average. This shows that when fruity and chocolate type flavors are in the same candy, more pounds of the candy are sold followed by only chocolate, followed by only fruity. 

```{R}
library(knitr)
library(stringr)
joined_candy %>% group_by(competitorname) %>% count -> table7
table7 %>% kable(digits = 3, align = 'c', col.names=str_to_title(names(.)))
joined_candy %>% group_by(State) %>% count 
```
There are only two character type variables in the joined dataset, competitorname and state. For competitor name, all of the candy counts are seen above for the 19 different candies, and there are no NAs present in this column. For state, all US states as well as Washington DC are included and each are only used once in the dataset. This column also does not have any NAs. 


#### Visualizing

```{R}
# your plot 1
```

Your discussion of plot 1

```{R}
# your plot 2
```

Your discussion of plot 2

```{R}
# your plot 3
```

Your discussion of plot 3

#### Concluding Remarks

If any!




